import type { VerticalConfig } from "./types.js";

export const movingVertical = {
  id: "moving",
  label: "Moving companies",
  version: 1,
  intakeFields: [
    {
      key: "pickupAddress",
      label: "Pickup address",
      question: "Where are you moving from?",
      valueType: "address",
      required: true,
    },
    {
      key: "dropoffAddress",
      label: "Drop-off address",
      question: "Where are you moving to?",
      valueType: "address",
      required: true,
    },
    {
      key: "movingDate",
      label: "Moving date",
      question: "What date would you like to move?",
      valueType: "date",
      required: true,
    },
    {
      key: "bedrooms",
      label: "Bedrooms",
      question: "How many bedrooms are in the home?",
      valueType: "integer",
      required: true,
      constraints: { min: 0, max: 20 },
    },
    {
      key: "pickupStairs",
      label: "Pickup stairs",
      question: "How many flights of stairs are at the pickup?",
      valueType: "integer",
      required: true,
      constraints: { min: 0, max: 100 },
    },
    {
      key: "dropoffStairs",
      label: "Drop-off stairs",
      question: "How many flights of stairs are at the destination?",
      valueType: "integer",
      required: true,
      constraints: { min: 0, max: 100 },
    },
    {
      key: "hasElevator",
      label: "Elevator access",
      question: "Is an elevator available at either address?",
      valueType: "boolean",
      required: true,
    },
    {
      key: "inventory",
      label: "Inventory",
      question: "Which large furniture, boxes, and other items are moving?",
      valueType: "inventory",
      required: true,
      constraints: { minLength: 1, maxLength: 500 },
    },
    {
      key: "specialItems",
      label: "Special items",
      question:
        "Are there pianos, safes, artwork, or other items needing special care?",
      valueType: "string-list",
      required: false,
      constraints: { maxLength: 200 },
    },
    {
      key: "packingPreference",
      label: "Packing",
      question: "Do you need packing help or packing materials?",
      valueType: "choice",
      required: true,
      options: [
        { label: "No packing help", value: "none" },
        { label: "Materials only", value: "materials" },
        { label: "Partial packing", value: "partial" },
        { label: "Full packing", value: "full" },
      ],
    },
    {
      key: "budget",
      label: "Target budget",
      question: "Do you have a target budget for the move?",
      valueType: "money",
      required: false,
      constraints: { min: 0 },
    },
    {
      key: "notes",
      label: "Additional notes",
      question: "Is there anything else a mover should know?",
      valueType: "text",
      required: false,
      constraints: { maxLength: 2_000 },
    },
  ],
  feeTaxonomy: [
    {
      code: "labor-hourly",
      label: "Hourly labor",
      description: "Crew labor billed by time.",
      category: "labor",
      unit: "person-hour",
      normallyApplies: "always",
      disclosureRequired: true,
    },
    {
      code: "minimum-hours",
      label: "Minimum hours",
      description: "Minimum billable crew time.",
      category: "labor",
      unit: "hour",
      normallyApplies: "conditional",
      disclosureRequired: true,
    },
    {
      code: "travel-time",
      label: "Travel time",
      description: "Time charged for the crew to reach or leave the job.",
      category: "transportation",
      unit: "hour",
      normallyApplies: "conditional",
      disclosureRequired: true,
    },
    {
      code: "mileage",
      label: "Mileage",
      description: "Distance-based vehicle charge.",
      category: "transportation",
      unit: "mile",
      normallyApplies: "conditional",
      disclosureRequired: true,
    },
    {
      code: "fuel",
      label: "Fuel surcharge",
      description: "Separate fuel or vehicle surcharge.",
      category: "transportation",
      unit: "flat",
      normallyApplies: "conditional",
      disclosureRequired: true,
    },
    {
      code: "stairs",
      label: "Stair carry",
      description: "Additional handling for stairs at either address.",
      category: "access",
      unit: "flat",
      normallyApplies: "conditional",
      disclosureRequired: true,
    },
    {
      code: "long-carry",
      label: "Long carry",
      description:
        "Additional handling when the truck cannot park near an entrance.",
      category: "access",
      unit: "flat",
      normallyApplies: "conditional",
      disclosureRequired: true,
    },
    {
      code: "elevator",
      label: "Elevator handling",
      description: "Charge for elevator access or wait time.",
      category: "access",
      unit: "flat",
      normallyApplies: "conditional",
      disclosureRequired: true,
    },
    {
      code: "packing-labor",
      label: "Packing labor",
      description: "Labor for packing or unpacking belongings.",
      category: "labor",
      unit: "hour",
      normallyApplies: "optional",
      disclosureRequired: true,
    },
    {
      code: "packing-materials",
      label: "Packing materials",
      description: "Boxes, wrapping, tape, and other consumable materials.",
      category: "materials",
      unit: "item",
      normallyApplies: "optional",
      disclosureRequired: true,
    },
    {
      code: "special-item",
      label: "Special-item handling",
      description:
        "Handling for pianos, safes, artwork, or similarly difficult items.",
      category: "special_handling",
      unit: "item",
      normallyApplies: "conditional",
      disclosureRequired: true,
    },
    {
      code: "valuation-coverage",
      label: "Valuation coverage",
      description: "Optional declared-value or enhanced protection coverage.",
      category: "coverage",
      unit: "flat",
      normallyApplies: "optional",
      disclosureRequired: true,
    },
    {
      code: "deposit",
      label: "Deposit",
      description: "Upfront amount required to reserve the move.",
      category: "administrative",
      unit: "percent",
      normallyApplies: "conditional",
      disclosureRequired: true,
    },
  ],
  benchmarks: [
    {
      id: "local-crew-hourly-rate",
      label: "Local crew hourly rate",
      context:
        "Broad demo-only guardrail for a local two-person crew; replace with sourced regional data.",
      range: { min: 90, max: 250 },
      unit: "usd-per-hour",
      reviewBeforeUse: true,
    },
    {
      id: "minimum-billable-time",
      label: "Minimum billable time",
      context: "Demo-only range for detecting unusually restrictive minimums.",
      range: { min: 2, max: 4 },
      unit: "hours",
      reviewBeforeUse: true,
    },
    {
      id: "deposit-share",
      label: "Deposit share",
      context:
        "Demo risk threshold; legal and market expectations vary by location.",
      range: { min: 0, max: 25 },
      unit: "percent",
      reviewBeforeUse: true,
    },
  ],
  redFlagRules: [
    {
      id: "missing-written-total",
      severity: "high",
      message: "The quote has no written total or calculation basis.",
      condition: { kind: "missing-value", field: "totalAmount" },
    },
    {
      id: "undisclosed-fee",
      severity: "high",
      message:
        "A fee appeared without being disclosed in the quoted breakdown.",
      condition: { kind: "undisclosed-fee" },
    },
    {
      id: "large-deposit",
      severity: "high",
      message: "The requested deposit exceeds the demo risk threshold.",
      condition: {
        kind: "number-above",
        field: "depositPercent",
        threshold: 25,
      },
    },
    {
      id: "price-outlier",
      severity: "medium",
      message:
        "The total is far from comparable quotes and needs verification.",
      condition: { kind: "quote-outlier", deviationPercent: 30 },
    },
    {
      id: "license-unverified",
      severity: "high",
      message: "Required mover licensing has not been verified.",
      condition: { kind: "unverified-business", verification: "license" },
    },
    {
      id: "insurance-unverified",
      severity: "high",
      message: "Mover insurance has not been verified.",
      condition: { kind: "unverified-business", verification: "insurance" },
    },
  ],
  negotiationPolicy: {
    truthfulnessRequired: true,
    mayReferenceCompetitorQuoteOnlyWhenDocumented: true,
    requiredEvidence: [
      "itemized written quote or timestamped transcript",
      "explicit statement of included and excluded fees",
      "offer expiration or callback commitment",
    ],
    allowedConcessions: [
      "lower total price",
      "waived disclosed fee",
      "reduced deposit",
      "improved cancellation terms",
      "included packing materials",
      "written price cap",
    ],
  },
} as const satisfies VerticalConfig;
