/** Browser-safe Relay design tokens mirrored by `@relay/ui/styles.css`. */
export const relayTokens = {
  accent: "#3157f6",
  accentSoft: "#eef1ff",
  background: "#f5f4ef",
  brandMint: "#86e6b3",
  border: "#e5e3dc",
  borderStrong: "#d4d1c8",
  leadingBody: "1.55",
  leadingHeading: "1.25",
  leadingMeta: "1.4",
  leadingTight: "1.1",
  muted: "#666a73",
  pageGutter: "40px",
  pageGutterMobile: "16px",
  pageGutterTablet: "24px",
  radiusLarge: "24px",
  radiusMedium: "16px",
  radiusSmall: "10px",
  shadowCard: "0 1px 2px rgb(15 23 42 / 4%), 0 12px 38px rgb(15 23 42 / 5%)",
  space1: "4px",
  space2: "8px",
  space3: "12px",
  space4: "16px",
  space5: "20px",
  space6: "24px",
  space8: "32px",
  space10: "40px",
  space12: "48px",
  space16: "64px",
  space24: "96px",
  success: "#16835c",
  successSoft: "#eaf9f1",
  surface: "#ffffff",
  text: "#101114",
  textBody: "0.9375rem",
  textCardTitle: "1rem",
  textControl: "0.875rem",
  textMeta: "0.75rem",
  textPageTitle: "clamp(2rem, 3vw, 2.75rem)",
  textSectionTitle: "1.25rem",
  warning: "#b86c0d",
  warningSoft: "#fff6e4",
  widthNarrow: "960px",
  widthStandard: "1200px",
  widthWide: "1360px",
} as const;

export type RelayTokenName = keyof typeof relayTokens;
export type RelayTokenValue = (typeof relayTokens)[RelayTokenName];

export const relayCssVariables = {
  accent: "--relay-accent",
  accentSoft: "--relay-accent-soft",
  background: "--relay-bg",
  brandMint: "--relay-brand-mint",
  border: "--relay-border",
  borderStrong: "--relay-border-strong",
  leadingBody: "--relay-leading-body",
  leadingHeading: "--relay-leading-heading",
  leadingMeta: "--relay-leading-meta",
  leadingTight: "--relay-leading-tight",
  muted: "--relay-muted",
  pageGutter: "--relay-page-gutter",
  pageGutterMobile: "--relay-page-gutter-mobile",
  pageGutterTablet: "--relay-page-gutter-tablet",
  radiusLarge: "--relay-radius-lg",
  radiusMedium: "--relay-radius-md",
  radiusSmall: "--relay-radius-sm",
  shadowCard: "--relay-shadow-card",
  space1: "--relay-space-1",
  space2: "--relay-space-2",
  space3: "--relay-space-3",
  space4: "--relay-space-4",
  space5: "--relay-space-5",
  space6: "--relay-space-6",
  space8: "--relay-space-8",
  space10: "--relay-space-10",
  space12: "--relay-space-12",
  space16: "--relay-space-16",
  space24: "--relay-space-24",
  success: "--relay-success",
  successSoft: "--relay-success-soft",
  surface: "--relay-surface",
  text: "--relay-text",
  textBody: "--relay-text-body",
  textCardTitle: "--relay-text-card-title",
  textControl: "--relay-text-control",
  textMeta: "--relay-text-meta",
  textPageTitle: "--relay-text-page-title",
  textSectionTitle: "--relay-text-section-title",
  warning: "--relay-warning",
  warningSoft: "--relay-warning-soft",
  widthNarrow: "--relay-width-narrow",
  widthStandard: "--relay-width-standard",
  widthWide: "--relay-width-wide",
} as const satisfies Readonly<Record<RelayTokenName, `--relay-${string}`>>;

export function relayTokenReference(
  token: RelayTokenName,
): `var(${(typeof relayCssVariables)[RelayTokenName]})` {
  return `var(${relayCssVariables[token]})`;
}
